[package]
name = "grid-search-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
itertools = "0.10.3"
rand = "0.8.5"
bitflags = "1.3.2"